apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      containers:
      - name: azure-devops-agent
        image: workflowstandard.azurecr.io/nginx
        env:
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: azure-devops-secret
              key: AZP_URL
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops-secret
              key: AZP_TOKEN
        - name: AZP_POOL
          valueFrom:
            secretKeyRef:
              name: azure-devops-secret
              key: AZP_POOL
      imagePullSecrets:
      - name: acr-auth
